import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Pricing Page",
  description: "Generated by create Pricing Page",
};

export default function PricingPage() {
  return (
    <>
      <main>
        <span className="text-7xl"> Pricing Page</span>
      </main>
    </>
  );
}
